### ISSUE TITLE
Can not link to Hue Hub

### ISSUE THREAD

**Issue by randalfox** [infofiend/Hue_B_Smart#12]
When trying to link to Hue hub I get an error in the Smartthings app that access is denied after pressing link button on Hue Hub. Below is an excerpt from my log file.

Thanks for any help you can provide and this application,
Please let me know if you need any additional info,
Randy Fox
Randalfox@me.com

5bf572f5-543a-4e2f-897a-e6c65f767be5  11:09:54 PM: debug getChildDevices(false), children=7
4ac587a0-271d-4a04-9ae6-701e951d7cf3  11:09:35 PM: info ||| NST Manager | Updating Structure Data (Last Updated: 180 seconds ago) | Updating Device Data (Last Updated: 180 seconds ago) (async)
813d1769-58cf-40e6-8d26-5768719f0743  11:08:59 PM: debug Parse returned {{ linkText }} has arrived
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:43 PM: error org.springframework.security.access.AccessDeniedException: Access is denied @ line 190
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:43 PM: debug bridge.value.serialNumber = 00178823607e ******************
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:43 PM: debug state.host = 192.168.0.21:80 ******************
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:43 PM: debug state.user = eEXNs7s5IPL3FNXRUDMkLOi8dKn-6xGJ1Hvg4XNp ******************
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:43 PM: debug bridge uuid:2f402f80-da50-11e1-9b23-00178823607e={ssdpUSN=uuid:2f402f80-da50-11e1-9b23-00178823607e, itemsDiscovered=false, networkAddress=C0A80015, ssdpNTS=null, serialNumber=00178823607e, mac=00178823607E, deviceAddress=0050, hub=67ded802-dc6c-4cce-b57d-a078c51f6bc4, ssdpPath=/description.xml, ssdpTerm=urn:schemas-upnp-org:device:basic:1, stringCount=04, verified=true, name=Philips hue (192.168.0.21), devicetype=04}
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:43 PM: debug username eEXNs7s5IPL3FNXRUDMkLOi8dKn-6xGJ1Hvg4XNp
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:43 PM: debug ssdp uuid:2f402f80-da50-11e1-9b23-00178823607e
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:43 PM: debug Bridge linked!
0d0a880a-ac99-4867-9d6e-772f0905fcde  11:08:43 PM: error java.lang.ArrayIndexOutOfBoundsException: 1 @ line 1393
0d0a880a-ac99-4867-9d6e-772f0905fcde  11:08:43 PM: debug Installed with settings: [:]
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:40 PM: debug linkButton [id:488f2dd0-fe3d-4823-be74-ece5cc8187e1, linkingBridge:true, ssdpUSN:uuid:2f402f80-da50-11e1-9b23-00178823607e, name:linkButton, mac:00178823607E, ip:192.168.0.21]
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:40 PM: debug Sending developer request to 192.168.0.21:80 (00178823607E)
488f2dd0-fe3d-4823-be74-ece5cc8187e1  11:08:36 PM: debug linkButton [id:488f2dd0-fe3d-4823-be74-ece5cc8187e1, linkingBridge:true,

**Comment by m31nyk** [comment]
I have the same issue. App stopped working so did a fresh install and now it won't let me link the bridge.

**Comment by randalfox** [comment]
I was able to get mine working by utilizing TMLEAFS Forked Repository of Hue_B_Smart. Thanks!
