### ISSUE TITLE
Flashing a Hue White Ambiance bulb causes a flashing loop

### ISSUE THREAD

**Issue by haXs** [infofiend/Hue_B_Smart#3]
I added a group containing 1 Hue White Ambiance bulb and selected the flash option on the tile and it triggered a rapid flashing loop, at one point it got so fast I had to switch the bulb off at the switch and remove the group from the smart app to resolve.

This bulb/room is also controlled  by a Hue motion sensor which automatically turns it off after 1 minute of inactivity but the flashing loop started instantly. This was an extract from the IDE logs:

e4d040d2-1eac-4cf2-bb4b-92e0cc13e824  6:35:45 PM: trace Hue B Smart Lux Group: flash():
e4d040d2-1eac-4cf2-bb4b-92e0cc13e824  6:35:45 PM: trace Hue B Smart Lux Group: updateStatus ( alert:lselect )
b75e6be3-1d1d-4633-a18f-08ab1abfaef7  6:35:44 PM: debug GROUP: devId = 0017882B83F3/GROUP3
b75e6be3-1d1d-4633-a18f-08ab1abfaef7  6:35:44 PM: debug k = /groups/3/action/alert, split1 = groups, split2 = 3, split3 = action, split4= alert, value = lselect
b75e6be3-1d1d-4633-a18f-08ab1abfaef7  6:35:44 PM: trace [/groups/3/action/alert:lselect]
e4d040d2-1eac-4cf2-bb4b-92e0cc13e824  6:35:44 PM: trace Hue B Smart Lux Group: flash():
e4d040d2-1eac-4cf2-bb4b-92e0cc13e824  6:35:44 PM: trace Hue B Smart Lux Group: updateStatus ( alert:lselect )
b75e6be3-1d1d-4633-a18f-08ab1abfaef7  6:35:44 PM: debug GROUP: devId = 0017882B83F3/GROUP3
b75e6be3-1d1d-4633-a18f-08ab1abfaef7  6:35:44 PM: debug k = /groups/3/action/alert, split1 = groups, split2 = 3, split3 = action, split4= alert, value = lselect
b75e6be3-1d1d-4633-a18f-08ab1abfaef7  6:35:44 PM: trace [/groups/3/action/alert:lselect]
e4d040d2-1eac-4cf2-bb4b-92e0cc13e824  6:35:44 PM: trace Hue B Smart Lux Group: flash():
e4d040d2-1eac-4cf2-bb4b-92e0cc13e824  6:35:44 PM: trace Hue B Smart Lux Group: updateStatus ( alert:lselect )
1bd3e7c4-2685-4c37-9750-8c8deda3f213  6:35:44 PM: trace getPhrases(), state.welcomeIssue = null
b75e6be3-1d1d-4633-a18f-08ab1abfaef7  6:35:43 PM: debug GROUP: devId = 0017882B83F3/GROUP3
b75e6be3-1d1d-4633-a18f-08ab1abfaef7  6:35:43 PM: debug k = /groups/3/action/alert, split1 = groups, split2 = 3, split3 = action, split4= alert, value = lselect

**Comment by mattjmiddleton** [comment]
You may want to make sure your DTH's are up to date, and if they are then ensure the bulbs are of the correct type - the above mentions:
race Hue B Smart Lux Group: flash():
Hue B Smart Lux Group: updateStatus 

If the bulbs are ambiance then you should change this in the IDE from devices / edit device to Hue B Smart Ambiance Bulb.

cheers
matt

**Comment by haXs** [comment]
I can confirm I have the most recent DTH's - for some reason they are being discovered as LUX bulbs when they are not. Changing them as you suggested resolved it

**Comment by mattjmiddleton** [comment]
glad it's working now.
cheers
matt
